### ISSUE TITLE
Unable to get updated sync token from CollectionPageIterator

### ISSUE THREAD

**Issue by williamjulianvicary** [Asana/php-asana#68]
The standard response from a getEvents request is a CollectionPageIterator however this does not handle the persistence of the sync token received from the API and it is therefore not possible to persist this value easily, without dropping the iterator (and it's helper methods) entirely.

A potential solution to this would be to update the CollectionPageIterator code to:
```
class CollectionPageIterator extends PageIterator
{
    public $sync = null;

    protected function getInitial()
    {
        return $this->client->get($this->path, $this->query, $this->options);
    }

    protected function getNext()
    {
        $this->options['offset'] = $this->continuation->offset;
        return $this->client->get($this->path, $this->query, $this->options);
    }

    protected function getContinuation($result)
    {
        if ($result->sync ?? null) {
            $this->sync = $result->sync;
        }

        return isset($result->next_page) ? $result->next_page : null;
    }
}
```

Then when making a request a user can do this:
```
$pageIterator = $client->events->getEvents(['resource' => 'resource-gid', 'sync' => 'my-sync-token'], ['iterator_type' => 'pages']);
$items = iterator_to_array($pageIterator->items());
$sync = $pageIterator->sync;
// Persist sync token for later use.
```

There is of course a better approach than this, but a simple quick fix for anyone looking the above should work!

**Comment by rossgrambo** [comment]
Thank you @williamjulianvicary,

You're absolutely right, the generated code doesn't page correctly. I'll create a task for updating this logic. I may end up using exactly what you proposed, but I'm going to check a couple of alternatives first.

Best,
Ross

**Comment by rossgrambo** [comment]
Should be resolved in 0.10.1

**Comment by Stdubic** [comment]
@rossgrambo and @williamjulianvicary I am experiencing issues with events going as @williamjulianvicary describe but have InvalidTokenError (code: 500) when trying:

$items = iterator_to_array($pageIterator->items());

can you please describe how to fix this issue or if is still an issue to try with raw req with events?
